name: 'dbt_sqlserver_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_airflow_project'

# Đưa các thư mục sinh ra trong quá trình build (packages/target) ra /tmp để tránh
# quyền sở hữu từ host bind-mount (Windows -> root trong container) gây lỗi Permission denied.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

packages-install-path: "/tmp/dbt_packages_cache"
target-path: "/tmp/dbt_target"
clean-targets:
  - "/tmp/dbt_target"
  - "/tmp/dbt_packages_cache"

models:
  dbt_sqlserver_project:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table 
      +schema: gold
