dbt_airflow_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "{{ env_var('DBT_SQLSERVER_DRIVER', 'ODBC Driver 18 for SQL Server') }}"
      server: "{{ env_var('DBT_SQLSERVER_HOST', 'sqlserver') }}"  # override in CI: localhost
      port: 1433
      database: "{{ env_var('DBT_SQLSERVER_DATABASE', 'AdventureWorks2014') }}"
      schema: "{{ env_var('DBT_SQLSERVER_SCHEMA', 'dbo') }}"
      user: "{{ env_var('DBT_SQLSERVER_USER', 'SA') }}"
      password: "{{ env_var('DBT_SQLSERVER_PASSWORD', 'YourStrong@Passw0rd') }}"
      windows_login: False
      encrypt: False
      trust_cert: True
      threads: 4  # Number of concurrent operations
      timeout_seconds: 300  # Query timeout in seconds
      retries: 3  # Number of retries for failed operations
      authentication: sql  # Explicitly specify SQL authentication
      keepalives_idle: 0  # Disable keepalive to prevent connection issues
      application_name: dbt_airflow_project  # Identify the application in SQL Server
      retry_on_error: True  # Enable automatic retries on transient errors 
    prod:
      type: sqlserver
      driver: "{{ env_var('DBT_SQLSERVER_DRIVER', 'ODBC Driver 18 for SQL Server') }}"
      server: "{{ env_var('DBT_SQLSERVER_HOST', 'sqlserver') }}"
      port: 1433
      database: "{{ env_var('DBT_SQLSERVER_DATABASE', 'AdventureWorks2014') }}"
      schema: "{{ env_var('DBT_SQLSERVER_SCHEMA', 'dbo') }}"
      user: "{{ env_var('DBT_SQLSERVER_USER', 'SA') }}"
      password: "{{ env_var('DBT_SQLSERVER_PASSWORD', 'YourStrong@Passw0rd') }}"
      windows_login: False
      encrypt: False
      trust_cert: True
      threads: 4
      timeout_seconds: 300
      retries: 3
      authentication: sql
      keepalives_idle: 0
      application_name: dbt_airflow_project
      retry_on_error: True
