version: 2

models:
  - name: gld_customer_metrics
    description: Customer-level aggregated metrics and KPIs
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('slvr_customers')
              field: customer_id
      - name: full_name
        description: Customer full name for reporting
      - name: territory_id
        description: Sales territory for the customer
      - name: total_orders
        description: Total number of orders placed
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue from customer
        tests:
          - not_null
      - name: avg_order_value
        description: Average order value across all orders
      - name: total_items_purchased
        description: Total quantity of items purchased
        tests:
          - not_null
      - name: first_order_date
        description: First order date
      - name: last_order_date
        description: Most recent order date
      - name: orders_with_discount
        description: Count of orders where a discount was applied
        tests:
          - not_null

  - name: gld_product_performance
    description: Product-level sales performance and profitability metrics
    columns:
      - name: product_id
        description: Unique product identifier
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('slvr_products')
              field: product_id
      - name: product_name
        description: Product name
      - name: subcategory_name
        description: Subcategory label for the product
      - name: color
        description: Product color
      - name: list_price
        description: Product list price
      - name: standard_cost
        description: Standard cost for the product
      - name: total_orders
        description: Total number of orders containing the product
        tests:
          - not_null
      - name: total_quantity_sold
        description: Total units sold
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue generated by the product
        tests:
          - not_null
      - name: avg_selling_price
        description: Average selling price across orders
        tests:
          - not_null
      - name: total_profit
        description: Profit calculated from revenue minus standard cost
        tests:
          - not_null
      - name: profit_margin_pct
        description: Profit margin percentage
        tests:
          - not_null

  - name: gld_sales_summary
    description: Daily sales summary with key business metrics
    columns:
      - name: order_date
        description: Date of orders
        tests:
          - unique
          - not_null
      - name: total_orders
        description: Total number of orders for the day
        tests:
          - not_null
      - name: unique_customers
        description: Number of unique customers who ordered
      - name: total_items_sold
        description: Total quantity of items sold
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue for the day
        tests:
          - not_null
      - name: avg_order_line_value
        description: Average revenue per order line
      - name: online_orders
        description: Count of online orders
        tests:
          - not_null
      - name: offline_orders
        description: Count of offline orders
        tests:
          - not_null
      - name: discounted_revenue
        description: Revenue attributed to discounted lines
        tests:
          - not_null
